---
# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11

    working_directory: /go/src/github.com/dgarage/dlc
    steps:
      - checkout
      - run:
          name: dependency-installation
          command: |
            dep ensure
      - run:
          name: test
          command: go test -v ./...
      - run:
          name: linter-installation
          command: |
            go get -v github.com/alecthomas/gometalinter
            gometalinter --install
            go get -u github.com/bradleyfalzon/revgrep/...
      - run:
          name: linter
          command: |
            set +o pipefail
            gometalinter --vendor --enable-all ./... |& revgrep master
